CREATE TABLE IF NOT EXISTS acceptance_tickets (
  id                 VARCHAR(128) NOT NULL PRIMARY KEY,
  requirement_id     VARCHAR(64)  NOT NULL,
  wide_table_id      VARCHAR(64)  NULL,
  task_group_id      VARCHAR(64)  NULL,
  scope_type         VARCHAR(32)  NOT NULL DEFAULT 'task_group',
  scope_key          VARCHAR(128) NOT NULL,
  dataset            VARCHAR(255) NULL,
  owner              VARCHAR(128) NULL,
  reviewer           VARCHAR(128) NULL,
  status             VARCHAR(32)  NOT NULL DEFAULT 'pending',
  feedback           TEXT         NULL,
  row_ids_json       JSON         NULL,
  publish_job_id     VARCHAR(128) NULL,
  publish_error_msg  TEXT         NULL,
  approved_at        DATETIME     NULL,
  published_at       DATETIME     NULL,
  latest_action_at   DATETIME     NULL,
  created_at         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_acceptance_tickets_scope (requirement_id, scope_type, scope_key),
  INDEX idx_acceptance_tickets_requirement (requirement_id),
  INDEX idx_acceptance_tickets_wide_table (wide_table_id),
  INDEX idx_acceptance_tickets_task_group (task_group_id),
  INDEX idx_acceptance_tickets_status (status),
  INDEX idx_acceptance_tickets_latest_action (latest_action_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
