-- Full backend DB schema for Data Foundry (MySQL)
-- Generated by transforming legacy FastAPI(SQLite) seed shape into MySQL tables.
--
-- Notes:
-- 1) This script is intended for local/dev usage to reproduce legacy sample pages.
-- 2) It DROPS tables (data will be wiped). Do not run in production.
-- 3) DB name is assumed: data_foundry_backend (set via `USE ...` before sourcing).

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS wide_table_row_snapshots;
DROP TABLE IF EXISTS wide_table_rows;
DROP TABLE IF EXISTS wide_table_scope_imports;
DROP TABLE IF EXISTS retrieval_tasks;
DROP TABLE IF EXISTS execution_records;
DROP TABLE IF EXISTS fetch_tasks;
DROP TABLE IF EXISTS task_groups;
DROP TABLE IF EXISTS collection_batches;
DROP TABLE IF EXISTS backfill_requests;
DROP TABLE IF EXISTS wide_tables;
DROP TABLE IF EXISTS preprocess_rules;
DROP TABLE IF EXISTS audit_rules;
DROP TABLE IF EXISTS knowledge_bases;
DROP TABLE IF EXISTS requirements;
DROP TABLE IF EXISTS projects;

CREATE TABLE projects (
  id                  VARCHAR(64)   NOT NULL PRIMARY KEY,
  sort_order          INT           NOT NULL DEFAULT 0,
  name                VARCHAR(255)  NOT NULL,
  created_by          VARCHAR(255)  NOT NULL DEFAULT '',
  owner_team          VARCHAR(255)  NOT NULL DEFAULT '',
  description         TEXT          NULL,
  status              VARCHAR(32)   NOT NULL DEFAULT 'active',
  business_background TEXT          NULL,
  -- Compatible with current Java backend mapper column: `data_source`
  data_source         JSON          NULL,
  created_at          DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_projects_sort_order (sort_order),
  INDEX idx_projects_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE requirements (
  id                        VARCHAR(64)   NOT NULL PRIMARY KEY,
  sort_order                INT           NOT NULL DEFAULT 0,
  project_id                VARCHAR(64)   NOT NULL,
  title                     VARCHAR(255)  NOT NULL,
  phase                     VARCHAR(32)   NOT NULL DEFAULT 'demo',
  parent_requirement_id     VARCHAR(64)   NULL,
  schema_locked             TINYINT(1)    NULL,
  status                    VARCHAR(32)   NOT NULL DEFAULT 'draft',
  owner                     VARCHAR(255)  NULL,
  assignee                  VARCHAR(255)  NULL,
  business_goal             TEXT          NULL,
  background_knowledge      TEXT          NULL,
  business_boundary         TEXT          NULL,
  delivery_scope            TEXT          NULL,
  data_update_enabled       TINYINT(1)    NULL,
  data_update_mode          VARCHAR(32)   NULL,
  processing_rule_drafts    JSON          NULL,
  -- Compatible with current Java backend mapper column: `collection_policy`
  collection_policy         JSON          NULL,
  created_at                DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at                DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_requirements_project_id (project_id),
  INDEX idx_requirements_parent_id (parent_requirement_id),
  INDEX idx_requirements_sort_order (sort_order),
  INDEX idx_requirements_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE wide_tables (
  id                      VARCHAR(64)   NOT NULL PRIMARY KEY,
  sort_order              INT           NOT NULL DEFAULT 0,
  requirement_id          VARCHAR(64)   NOT NULL,
  title                   VARCHAR(255)  NOT NULL,
  description             TEXT          NULL,
  table_name              VARCHAR(255)  NOT NULL,
  schema_version          INT           NOT NULL DEFAULT 1,
  schema_json             JSON          NULL,
  scope_json              JSON          NULL,
  indicator_groups_json   JSON          NULL,
  schedule_rules_json     JSON          NULL,
  semantic_time_axis      VARCHAR(32)   NULL,
  collection_coverage_mode VARCHAR(64)  NULL,
  status                  VARCHAR(32)   NOT NULL DEFAULT 'active',
  record_count            INT           NOT NULL DEFAULT 0,
  created_at              DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at              DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_wide_tables_requirement_id (requirement_id),
  INDEX idx_wide_tables_sort_order (sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE wide_table_scope_imports (
  wide_table_id           VARCHAR(64)   NOT NULL PRIMARY KEY,
  requirement_id          VARCHAR(64)   NOT NULL,
  import_mode             VARCHAR(64)   NOT NULL,
  file_name               VARCHAR(255)  NOT NULL,
  file_type               VARCHAR(128)  NOT NULL COMMENT '导入文件类型或 MIME 类型',
  content_hash            VARCHAR(64)   NULL,
  row_count               INT           NOT NULL DEFAULT 0,
  header_json             JSON          NULL,
  file_content            MEDIUMTEXT    NULL,
  created_by              VARCHAR(255)  NULL,
  created_at              DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at              DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_wide_table_scope_imports_wide_table
    FOREIGN KEY (wide_table_id) REFERENCES wide_tables(id) ON DELETE CASCADE,
  INDEX idx_wide_table_scope_imports_requirement_id (requirement_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE wide_table_rows (
  wide_table_id           VARCHAR(64)   NOT NULL,
  row_id                  INT           NOT NULL,
  sort_order              INT           NOT NULL DEFAULT 0,
  requirement_id          VARCHAR(64)   NOT NULL,
  schema_version          INT           NOT NULL DEFAULT 1,
  plan_version            INT           NOT NULL DEFAULT 1,
  row_status              VARCHAR(32)   NOT NULL DEFAULT 'initialized',
  dimension_values_json   JSON          NULL,
  -- Legacy seed uses mixed formats: YYYY-MM-DD / YYYY / YYYY-Q4
  business_date           VARCHAR(32)   NULL,
  row_binding_key         VARCHAR(512)  NULL,
  indicator_values_json   JSON          NULL,
  system_values_json      JSON          NULL,
  PRIMARY KEY (wide_table_id, row_id),
  INDEX idx_wtr_requirement_id (requirement_id),
  INDEX idx_wtr_business_date (business_date),
  INDEX idx_wtr_row_binding_key (row_binding_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE wide_table_row_snapshots (
  batch_id                VARCHAR(64)   NOT NULL,
  wide_table_id           VARCHAR(64)   NOT NULL,
  row_id                  INT           NOT NULL,
  row_binding_key         VARCHAR(512)  NULL,
  -- Legacy seed uses mixed formats: YYYY-MM-DD / YYYY / YYYY-Q4
  business_date           VARCHAR(32)   NULL,
  row_status              VARCHAR(32)   NOT NULL DEFAULT 'initialized',
  dimension_values_json   JSON          NULL,
  indicator_values_json   JSON          NULL,
  system_values_json      JSON          NULL,
  created_at              DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at              DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (batch_id, wide_table_id, row_id),
  INDEX idx_wtrs_wide_table_id (wide_table_id),
  INDEX idx_wtrs_business_date (business_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE backfill_requests (
  id                  VARCHAR(64)  NOT NULL PRIMARY KEY,
  sort_order          INT          NOT NULL DEFAULT 0,
  requirement_id      VARCHAR(64)  NOT NULL,
  wide_table_id       VARCHAR(64)  NOT NULL,
  -- Legacy seed uses mixed formats: YYYY-MM-DD / YYYY / YYYY-Q4
  start_business_date VARCHAR(32)  NULL,
  end_business_date   VARCHAR(32)  NULL,
  requested_by        VARCHAR(64)  NULL,
  origin              VARCHAR(32)  NULL,
  status              VARCHAR(32)  NOT NULL DEFAULT 'pending',
  reason              TEXT         NULL,
  INDEX idx_bfr_requirement_id (requirement_id),
  INDEX idx_bfr_wide_table_id (wide_table_id),
  INDEX idx_bfr_sort_order (sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE collection_batches (
  id                 VARCHAR(64)  NOT NULL PRIMARY KEY,
  sort_order         INT          NOT NULL DEFAULT 0,
  requirement_id     VARCHAR(64)  NOT NULL,
  wide_table_id      VARCHAR(64)  NOT NULL,
  snapshot_at        DATETIME     NULL,
  snapshot_label     VARCHAR(64)  NULL,
  coverage_mode      VARCHAR(64)  NULL,
  semantic_time_axis VARCHAR(32)  NULL,
  status             VARCHAR(32)  NOT NULL DEFAULT 'pending',
  is_current         TINYINT(1)   NOT NULL DEFAULT 0,
  plan_version       INT          NOT NULL DEFAULT 1,
  triggered_by       VARCHAR(64)  NULL,
  -- Legacy seed uses mixed formats: YYYY-MM-DD / YYYY / YYYY-Q4
  start_business_date VARCHAR(32) NULL,
  end_business_date   VARCHAR(32) NULL,
  created_at         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_cb_requirement_id (requirement_id),
  INDEX idx_cb_wide_table_id (wide_table_id),
  INDEX idx_cb_is_current (is_current),
  INDEX idx_cb_sort_order (sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE task_groups (
  id                 VARCHAR(64)  NOT NULL PRIMARY KEY,
  sort_order          INT         NOT NULL DEFAULT 0,
  requirement_id      VARCHAR(64) NOT NULL,
  wide_table_id       VARCHAR(64) NOT NULL,
  batch_id            VARCHAR(64) NULL,
  -- Legacy seed uses mixed formats: YYYY-MM-DD / YYYY / YYYY-Q4
  business_date       VARCHAR(32) NULL,
  source_type         VARCHAR(32) NULL,
  status              VARCHAR(32) NOT NULL DEFAULT 'pending',
  schedule_rule_id    VARCHAR(64) NULL,
  backfill_request_id VARCHAR(64) NULL,
  plan_version        INT         NOT NULL DEFAULT 1,
  group_kind          VARCHAR(32) NULL,
  partition_type      VARCHAR(32) NULL,
  partition_key       VARCHAR(255) NULL,
  partition_label     VARCHAR(255) NULL,
  total_tasks         INT         NOT NULL DEFAULT 0,
  completed_tasks     INT         NOT NULL DEFAULT 0,
  failed_tasks        INT         NOT NULL DEFAULT 0,
  triggered_by        VARCHAR(64) NULL,
  created_at          DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_tg_requirement_id (requirement_id),
  INDEX idx_tg_wide_table_id (wide_table_id),
  INDEX idx_tg_batch_id (batch_id),
  INDEX idx_tg_business_date (business_date),
  INDEX idx_tg_sort_order (sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE fetch_tasks (
  id                    VARCHAR(128) NOT NULL PRIMARY KEY,
  sort_order            INT          NOT NULL DEFAULT 0,
  requirement_id        VARCHAR(64)  NOT NULL,
  wide_table_id         VARCHAR(64)  NOT NULL,
  task_group_id         VARCHAR(64)  NULL,
  batch_id              VARCHAR(64)  NULL,
  row_id                INT          NULL,
  indicator_group_id    VARCHAR(64)  NULL,
  indicator_group_name  VARCHAR(255) NULL,
  name                  VARCHAR(512) NULL,
  schema_version        INT          NOT NULL DEFAULT 1,
  execution_mode        VARCHAR(32)  NULL,
    indicator_keys_json   JSON         NULL,
    dimension_values_json JSON         NULL,
    rendered_prompt_text  LONGTEXT     NULL,
    prompt_template_snapshot LONGTEXT  NULL,
    collection_task_id    VARCHAR(128) NULL,
    -- Legacy seed uses mixed formats: YYYY-MM-DD / YYYY / YYYY-Q4
    business_date         VARCHAR(32)  NULL,
  status                VARCHAR(32)  NOT NULL DEFAULT 'pending',
  can_rerun             TINYINT(1)   NOT NULL DEFAULT 1,
  invalidated_reason    TEXT         NULL,
  owner                 VARCHAR(255) NULL,
  confidence            DECIMAL(5,2) NULL,
  plan_version          INT          NOT NULL DEFAULT 1,
  row_binding_key       VARCHAR(512) NULL,
  created_at            DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at            DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_ft_requirement_id (requirement_id),
  INDEX idx_ft_wide_table_id (wide_table_id),
  INDEX idx_ft_task_group_id (task_group_id),
  INDEX idx_ft_batch_id (batch_id),
  INDEX idx_ft_status (status),
  INDEX idx_ft_sort_order (sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE retrieval_tasks (
  id             VARCHAR(128) NOT NULL PRIMARY KEY,
  sort_order     INT          NOT NULL DEFAULT 0,
  parent_task_id VARCHAR(128) NOT NULL,
  wide_table_id  VARCHAR(64)  NOT NULL,
  row_id         INT          NULL,
  name           VARCHAR(255) NULL,
  indicator_key  VARCHAR(64)  NULL,
  query          TEXT         NULL,
  status         VARCHAR(32)  NOT NULL DEFAULT 'pending',
  confidence     DECIMAL(5,2) NULL,
  narrow_row_json JSON        NULL,
  INDEX idx_rt_parent_task_id (parent_task_id),
  INDEX idx_rt_wide_table_id (wide_table_id),
  INDEX idx_rt_sort_order (sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE execution_records (
  id          VARCHAR(128) NOT NULL PRIMARY KEY,
  sort_order  INT          NOT NULL DEFAULT 0,
  task_id     VARCHAR(128) NOT NULL,
  trigger_type VARCHAR(32) NOT NULL,
  status      VARCHAR(32)  NOT NULL,
  started_at  DATETIME     NULL,
  ended_at    DATETIME     NULL,
  operator    VARCHAR(64)  NULL,
  output_ref  VARCHAR(255) NULL,
  log_ref     VARCHAR(255) NULL,
  INDEX idx_er_task_id (task_id),
  INDEX idx_er_started_at (started_at),
  INDEX idx_er_sort_order (sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE knowledge_bases (
  id             VARCHAR(64)  NOT NULL PRIMARY KEY,
  name           VARCHAR(255) NOT NULL,
  description    TEXT         NULL,
  document_count INT          NOT NULL DEFAULT 0,
  status         VARCHAR(32)  NOT NULL DEFAULT 'ready',
  last_updated   DATETIME     NULL,
  INDEX idx_kb_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE preprocess_rules (
  id                     VARCHAR(64)  NOT NULL PRIMARY KEY,
  name                   VARCHAR(255) NOT NULL,
  source                 VARCHAR(32)  NULL,
  enabled                TINYINT(1)   NOT NULL DEFAULT 1,
  category               VARCHAR(32)  NULL,
  expression             TEXT         NULL,
  sample_issue           TEXT         NULL,
  indicator_bindings_json JSON        NULL,
  filling_config_json    JSON         NULL,
  INDEX idx_pr_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE audit_rules (
  id             VARCHAR(64)  NOT NULL PRIMARY KEY,
  name           VARCHAR(255) NOT NULL,
  mode           VARCHAR(32)  NULL,
  scenario_rigour VARCHAR(32) NULL,
  condition_expr TEXT         NULL,
  action_text    TEXT         NULL,
  enabled        TINYINT(1)   NOT NULL DEFAULT 1,
  INDEX idx_ar_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;
