package com.huatai.datafoundry.backend.requirement.infrastructure.persistence.mybatis.mapper;

import com.huatai.datafoundry.backend.requirement.infrastructure.persistence.mybatis.record.RequirementSearchRowRecord;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

@Mapper
public interface RequirementSearchMapper {

  @Select({
      "<script>",
      "select count(1)",
      "from requirements r",
      "left join projects p on p.id = r.project_id",
      "left join wide_tables wt on wt.requirement_id = r.id and wt.sort_order = 0",
      "where 1=1",
      "  <if test='projectId != null and projectId != \"\"'>",
      "    and r.project_id = #{projectId}",
      "  </if>",
      "  <if test='owner != null and owner != \"\"'>",
      "    and r.owner like concat('%', #{owner}, '%')",
      "  </if>",
      "  <if test='assignee != null and assignee != \"\"'>",
      "    and r.assignee like concat('%', #{assignee}, '%')",
      "  </if>",
      "  <if test='statuses != null and statuses.size() &gt; 0'>",
      "    and r.status in",
      "    <foreach collection='statuses' item='s' open='(' separator=',' close=')'>",
      "      #{s}",
      "    </foreach>",
      "  </if>",
      "  <if test='hasWideTable != null'>",
      "    <choose>",
      "      <when test='hasWideTable'>and wt.id is not null</when>",
      "      <otherwise>and wt.id is null</otherwise>",
      "    </choose>",
      "  </if>",
      "  <if test='wideTableId != null and wideTableId != \"\"'>",
      "    and wt.id = #{wideTableId}",
      "  </if>",
      "  <if test='wideTableKeyword != null and wideTableKeyword != \"\"'>",
      "    and (wt.id like concat('%', #{wideTableKeyword}, '%')",
      "      or wt.table_name like concat('%', #{wideTableKeyword}, '%'))",
      "  </if>",
      "  <if test='keyword != null and keyword != \"\"'>",
      "    and (",
      "      r.id like concat('%', #{keyword}, '%')",
      "      or r.title like concat('%', #{keyword}, '%')",
      "      or r.owner like concat('%', #{keyword}, '%')",
      "      or r.assignee like concat('%', #{keyword}, '%')",
      "      or p.name like concat('%', #{keyword}, '%')",
      "      or wt.id like concat('%', #{keyword}, '%')",
      "      or wt.table_name like concat('%', #{keyword}, '%')",
      "    )",
      "  </if>",
      "</script>",
  })
  long count(
      @Param("keyword") String keyword,
      @Param("projectId") String projectId,
      @Param("owner") String owner,
      @Param("assignee") String assignee,
      @Param("statuses") List<String> statuses,
      @Param("wideTableId") String wideTableId,
      @Param("wideTableKeyword") String wideTableKeyword,
      @Param("hasWideTable") Boolean hasWideTable);

  @Select({
      "<script>",
      "select",
      "  r.id as requirement_id,",
      "  r.project_id as project_id,",
      "  p.name as project_name,",
      "  r.title as title,",
      "  r.phase as phase,",
      "  r.status as status,",
      "  r.schema_locked as schema_locked,",
      "  r.owner as owner,",
      "  r.assignee as assignee,",
      "  r.created_at as created_at,",
      "  r.updated_at as updated_at,",
      "  wt.id as wide_table_id,",
      "  wt.table_name as wide_table_table_name,",
      "  wt.record_count as wide_table_record_count,",
      "  JSON_LENGTH(JSON_EXTRACT(wt.schema_json, '$.columns')) as wide_table_column_count",
      "from requirements r",
      "left join projects p on p.id = r.project_id",
      "left join wide_tables wt on wt.requirement_id = r.id and wt.sort_order = 0",
      "where 1=1",
      "  <if test='projectId != null and projectId != \"\"'>",
      "    and r.project_id = #{projectId}",
      "  </if>",
      "  <if test='owner != null and owner != \"\"'>",
      "    and r.owner like concat('%', #{owner}, '%')",
      "  </if>",
      "  <if test='assignee != null and assignee != \"\"'>",
      "    and r.assignee like concat('%', #{assignee}, '%')",
      "  </if>",
      "  <if test='statuses != null and statuses.size() &gt; 0'>",
      "    and r.status in",
      "    <foreach collection='statuses' item='s' open='(' separator=',' close=')'>",
      "      #{s}",
      "    </foreach>",
      "  </if>",
      "  <if test='hasWideTable != null'>",
      "    <choose>",
      "      <when test='hasWideTable'>and wt.id is not null</when>",
      "      <otherwise>and wt.id is null</otherwise>",
      "    </choose>",
      "  </if>",
      "  <if test='wideTableId != null and wideTableId != \"\"'>",
      "    and wt.id = #{wideTableId}",
      "  </if>",
      "  <if test='wideTableKeyword != null and wideTableKeyword != \"\"'>",
      "    and (wt.id like concat('%', #{wideTableKeyword}, '%')",
      "      or wt.table_name like concat('%', #{wideTableKeyword}, '%'))",
      "  </if>",
      "  <if test='keyword != null and keyword != \"\"'>",
      "    and (",
      "      r.id like concat('%', #{keyword}, '%')",
      "      or r.title like concat('%', #{keyword}, '%')",
      "      or r.owner like concat('%', #{keyword}, '%')",
      "      or r.assignee like concat('%', #{keyword}, '%')",
      "      or p.name like concat('%', #{keyword}, '%')",
      "      or wt.id like concat('%', #{keyword}, '%')",
      "      or wt.table_name like concat('%', #{keyword}, '%')",
      "    )",
      "  </if>",
      "order by",
      "  <choose>",
      "    <when test='sortBy == \"updated_at\"'>r.updated_at</when>",
      "    <when test='sortBy == \"created_at\"'>r.created_at</when>",
      "    <when test='sortBy == \"title\"'>r.title</when>",
      "    <when test='sortBy == \"project_name\"'>p.name</when>",
      "    <when test='sortBy == \"owner\"'>r.owner</when>",
      "    <when test='sortBy == \"assignee\"'>r.assignee</when>",
      "    <when test='sortBy == \"status\"'>r.status</when>",
      "    <when test='sortBy == \"wide_table_name\"'>wt.table_name</when>",
      "    <otherwise>r.updated_at</otherwise>",
      "  </choose>",
      "  <choose>",
      "    <when test='sortDir == \"asc\"'>asc</when>",
      "    <otherwise>desc</otherwise>",
      "  </choose>,",
      "  r.id desc",
      "limit #{limit} offset #{offset}",
      "</script>",
  })
  List<RequirementSearchRowRecord> list(
      @Param("keyword") String keyword,
      @Param("projectId") String projectId,
      @Param("owner") String owner,
      @Param("assignee") String assignee,
      @Param("statuses") List<String> statuses,
      @Param("wideTableId") String wideTableId,
      @Param("wideTableKeyword") String wideTableKeyword,
      @Param("hasWideTable") Boolean hasWideTable,
      @Param("sortBy") String sortBy,
      @Param("sortDir") String sortDir,
      @Param("offset") int offset,
      @Param("limit") int limit);
}
