server:
  port: 8000

spring:
  application:
    name: data-foundry-backend-service
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/data_foundry_backend?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: data_foundry_backend
    password: data_foundry_backend

mybatis:
  configuration:
    map-underscore-to-camel-case: true

data-foundry:
  scheduler:
    base-url: http://127.0.0.1:8200
